### ISSUE TITLE
 Feat: page-home Progressbar, Refactoring

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#103]
## ☕ 기능

- React Circular Progressbar 적용
- Home-page Refactoring
<img width="300" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/4580a063-c27b-48d5-8cef-3407edb20df4">

## 🪴 TODO

- [x] Chore: React Circular Progressbar
- [x] Feat: React Circular Progressbar
- [x] Fix: 사소한 수정
- [x] Feat: coffeeOptionSelection.tsx
- [x] Fix: setPostRegist
- [x] Refactor: home constants
- [x] Fix: getUserInfo
- [x] Feat: useResetSelectedCoffee
- [x] Feat:useGetUserInfo
- [x] Feat:useGetTodayCoffeeData
- [x] Feat: useGetCoffeeList
- [x] Refactor: getUserInfo api
