### ISSUE TITLE
 Feat: profile-page api 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#107]
## ☕ 기능

- profile page api 연결 및 리팩토링
- UI 깨짐 현상 수정
- profile post infinite query 적용

<img width="273" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/fab26884-3592-4c38-b0b9-59d8eb80becf">

## 🪴 TODO

- [x] Feat: FooterIcon getUserId
- [x] Refactor: 사소한 수정
- [x] Refactor: type 수정
- [x] Refactor: FollowCount.tsx
- [x] Feat: ProfilePosts infiniteQuery
- [x] Refactor: PostRegister
- [x] Design: WaterPerCoffee.tsx
- [x] Refactor: FooterIcon route data(userId)
- [x] Refactor: ProfileDetail.tsx && getUserInfo
- [x] Refactor: type 수정
- [x] Feat: getUserFollowsCount
- [x] Feat: getUserPosts
