### ISSUE TITLE
Fix: Home-page, Common

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#126]
## ☕ 기능

- Home-page 
  - !userInfo && null TypeError
  - weeklyPopular data fetching && !auth
  - waterPerCoffee data cacheing
  - coffeeOptions Max Shot Setting
  - Home page design
-  Common
   - AlretBubble
   - SelectBox && SelectBtn && SelectOption
 
<img width="600" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/6f7a8e02-0c5d-49e8-8459-3612508e4c29">
<img width="600" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/f67a177c-190d-46b2-b1d5-41e50226217d">

<img width="300" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/ae3c020e-25c3-4224-8a34-7873142de97d">

## 🪴 TODO

- [x] Fix: Home-Page TypeError
- [x] Feat:  weeklyPopular data fetching  && auth > base
- [x] Feat: WaterIntake && water data caching
- [x] Feat: CoffeeOptionSelector && max shot
- [x] Design: SelectBox Design
- [x] Feat: common && AlretBubble.tsx
- [x] Feat: useSelect.ts
- [x]  Feat: SelectBox && SelectBtn && SelectOption components
- [x] Refactor: CoffeeMenuSelection.tsx
- [x] Design: Page-Home.tsx
