### ISSUE TITLE
Fix: post detail 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#135]
## ☕ 기능

[Screen recording 2024-03-26 6.06.06 PM.webm](https://github.com/7-7-2/DDocker_FE/assets/115582699/d1e39baa-c952-4240-af0b-23d77cfb5afa)

## 🪴 TODO

- [x] 게시글 상세 댓글 없을시 텍스트 렌더링 
- [x] 게시글 삭제시 삭제 확인 컴포넌트 추가
- [x] 답글 작성 후 답글 선택 상태 리셋
