### ISSUE TITLE
Fix: brandPopularPosts 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#143]
## ☕ 기능

-  **로그인 유저 트렌드 진입시 선호 브랜드 초기값 설정 및 focus**
-  최신/인기 필터 변경에 따라 인기/최신 게시글 텍스트 변경

## 🪴 TODO

- [x] 로그인 유저 트렌드 진입시 선호 브랜드 초기값 설정
- [x] 최신/인기 필터 선택시 텍스트 변경
- [x] trend selected로 페이지 진입시 focus
