### ISSUE TITLE
 Refactor: profile-page && home-page CTA.tsx 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#147]
## ☕ 기능

 
<img width="320" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/cf961cdd-8a12-466d-a7a6-f2c692a97a8d">

- CTA.tsx 적용
- getMyInfo 분리
- gender data type 변경

## 🪴 TODO

- [x] Refactor: WaterPserCoffee && anonymousCard && CTA
- [x] Refactor: page-Profile && AnonymousUserCard.tsx
- [x] Feat: page-Profile && EmptyPostGrid.tsx && CTA
- [x] Refactor: Page-Profile.tsx && FollowCount, PostsGrid
- [x] Refactor: getMyInfo | getUserInfo routes
- [x] Fix: PostsGridProps type
- [x] Fix: gender data type
- [x] Design: 사소한 수정
