### ISSUE TITLE
Chore: custom hooks foldering 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#148]
## ☕ 기능

- custom hooks foldering

## 🪴 TODO

- [x] Chore: hooks && home folder foldering 
- [x] Chore: hooks && Profile folder foldering
- [x] Chore: hooks && start folder foldering
