### ISSUE TITLE
 Feat: MyCoffeeSum && activeMonth 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#164]
## ☕ 기능

<img width="336" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/d5a25422-f00e-4382-818c-5fb992c62e39">

- MyCoffeeSum && activeMonth 
- getCalendarData &&  maxDate, minDate 

## 🪴 TODO

- [x] Feat: MyCoffeeSum && activeMonth 
- [x] Fix:  getCalendarData &&  maxDate, minDate 
- [x] Fix: MyProfile && navigate
