### ISSUE TITLE
 Feat: Page - Home && Footer

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#166]
## ☕ 기능

<img width="297" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/0870b3eb-0818-43ad-8efa-8e9c513d69e2">

- Page-Home && HomeFooter

## 🪴 TODO

- [x] Design: Page-Home && HomeFooter
- [x] Refactor: getPopularList
- [x] Refactor: Home constants
- [x] Design: Page-start && selectFavBrand
