### ISSUE TITLE
 Feat: Page-Error

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#170]
## ☕ 기능

<img width="300" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/486b4da0-2d2a-4601-9f37-0d1770ddf36f">

- Page-Error

## 🪴 TODO

- [x] Feat: Page-Error
- [x] Fix: Page-Home && WaterIntake
- [x] Refactor: Page-home &&  HomeFooter
