### ISSUE TITLE
Fix: gender type to aboutMe

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#177]
## ☕ 기능

- 회원가입 프로세스내 남자/여자(boolean)값 제거 후 abotuMe입력으로 대체

## 🪴 TODO

- [x] Fix: delete gender constants && start.ts
- [x] Feat: convertUserAboutMe.ts
- [x] Feat: initialForm.tsx && userAboutMe
- [x] Fix: delete SelectGender.tsx && gender data
