### ISSUE TITLE
 Feat: WaterIntake  && cachedData , WeeklyPopular  && getWeeklyPopularList

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#184]
## ☕ 기능

- waterIntake cachedData 수정
   - 'water/${userId}'
- WeeklyPopular && getWeeklyPopularList
   - 자정에 데이터 refetch
  

## 🪴 TODO

- [x] Fix: 사소한 수정
- [x] Fix: HomeFooter && category key
- [x] Feat: WeeklyPopular && useGetPopularList
- [x] Feat: WaterIntake && useGetCachedWater
