### ISSUE TITLE
 Feat: signOut && deleteAccount 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#192]
## ☕ 기능

<img width="234" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/1f67af17-6081-46de-977e-3bd4c4fb83f2">

- 로그아웃 기능 구현
- 회원탈퇴 기능 구현 및 탈퇴 확인 모달
   -  회원탈퇴 api 연결
   - myPage 버튼 추가
   - 탈퇴 확인 모달 추가

## 🪴 TODO

- [x] Feat: useHandleAuth
- [x] Design: MyProfile && signOutBtn && deleteAccountBtn
- [x] Feat: deleteUserAccount.api
- [x] Feat: deleteUserAccount.api
- [x] Fix: 닉네임 유효성 검사 수정 및 사소한 수정
