### ISSUE TITLE
Fix: remove delete user data from storage

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#205]
## ☕ 기능

- 회원탈퇴시 스토리지 내 users/ post/ 이미지 삭제

## 🪴 TODO

- [x] ConfirmDeleteUser.tsx 내 상수 분리
- [x] ```const { deleteStorage } = useCloudStorage();``` 재사용
- [x] Feat: deleteAccount => deleteStorage(profile,posts)
- [x] Feat: deleteAllFolderItems && deleteFolder
- [x] Refactor: confirmDeleteUser constants
