### ISSUE TITLE
Feat: display default image on user without profileImg

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#215]
## ☕ 기능
![Screenshot 2024-05-17 10 49 41 PM](https://github.com/7-7-2/DDocker_FE/assets/115582699/d1ebeae9-e072-4feb-91ee-d9fde34830d0)
![Screenshot 2024-05-17 10 49 31 PM](https://github.com/7-7-2/DDocker_FE/assets/115582699/aeb336d9-b672-4dfb-ad14-d15f0d4f32c3)
![Screenshot 2024-05-17 10 49 17 PM](https://github.com/7-7-2/DDocker_FE/assets/115582699/28137a5f-3825-4236-ba3c-aaa70ded92d2)
![Screenshot 2024-05-17 10 48 58 PM](https://github.com/7-7-2/DDocker_FE/assets/115582699/a44a74cd-8bf0-49e7-9398-b8dd2de76a0a)

1. 기존 회원가입시 기본 프로필 사진 social auth(kakao,google) 프로필 이미지 사용  => 기본 이미지 설정
2. 기존 cloudflare이미지 경로 요청 + db내 profile경로 => profile경로 요청 제거 후 기본 이미지 사용

## 🪴 TODO

- [x] 기본 이미지 설정 후 사용(sprite.svg) 
- [x] 프로필 이미지 요청 코드 제거(notification)  => ```onError 함수 제거 후 svg이미지```  
- [x] 이미지 컨테이너 크기별 설정(36,40,44)
