### ISSUE TITLE
 Feat: CustomerSupport

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#217]
## ☕ 기능

<img width="739" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/9442d391-253a-45f1-8ebd-a9e6035e2d46">

- Customer Support Page

## 🪴 TODO

- [ ] Feat: connect Notices to getSupportList API && NoticeDetail to getNoticeDetail API
- [ ] Feat: Connect FAQ and FoldableCard to getSupportList API
- [ ] Rename: report => support
- [ ] Fix: SearchBar add Props && FAQ add searchFun
- [ ] Design: FAQ.tsx && FoldableCard.tsx
- [ ] Feat: Notice.tsx && NoticeDetail.tsx
- [ ] Refactor: Page-Follow && FollowTab => Tabs
- [ ] Feat: Taps.tsx && useSelectTap.ts
- [ ] Rename: useSelect => useSelectBox
- [ ] Feat: Page-Support
