### ISSUE TITLE
 Feat: Page-support && TOS, PrivacyPolicy

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#228]
## ☕ 기능

- HomeFooter => support 각 페이지 연결
- 이용약관
- 개인정보처리방침

## 🪴 TODO

- [x] Feat: TOS.tsx && PrivacyPolicy.tsx
- [x] Feat: usePrintContents.ts && extractChpater.ts && ActionButtons.tsx
- [x] Feat: HomeFooter.tsx && Page-Support.tsx nav
- [x] Fix: deploy.yaml quote
- [x] Fix: userAboutMe type
