### ISSUE TITLE
 Fix: Page-home, Page-profile

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#230]
#### Page-Home
- coffeeMenuSelection.tsx > selectBox 
  - 브랜드 선택 전, 메뉴 선택 박스 disabled
  - 초기화 버튼 클릭 후에도 FavBrand 선택 유지 
- WaterIntake.tsx
#### Page-ProFile
- FollowCount > 팔로워 팔로잉 순서 변경

## 🪴 TODO

- [x] Feat: SelectBox,SelectBtn  && disabled
- [x] Refactor: useGetUserInfo
- [x] Fix: WaterIntake.tsx
- [x] Refactor: FollowCount constants && reorder
