### ISSUE TITLE
 Fix: null error 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#260]
## ☕ 기능

- null => 404 error 수정
- NoticeDetail.tsx 스타일 수정
- pwabuilder ASSETS 수정

## 🪴 TODO

- [x] Design: NoticeDetail.tsx
- [x] Fix: null error
- [x] Fix:Unified URL formatting
- [x] Fix: pwabuilder
