### ISSUE TITLE
 Fix:  add FAQ non-member text, weeklyPopularList design  

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#272]
## ☕ 기능

- add FAQ non-member text
- weeklyPopularList design 

## 🪴 TODO

- [x] Feat: FAQ non-member text
- [x] Design: weeklyPopularList design
- [x] Fix: Page-home && email text
- [x] Fix: PostComments
