### ISSUE TITLE
Fix: for beta service (design, error)

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#276]
## ☕ 기능

- 전반적인 스타일 수정
- getBrandPath 오타 수정
- weeklyPopularList item 조건문 추가

## 🪴 TODO

- [x] Design: for beta service
- [x] Fix: weeklyPopularList, getBrandpath
- [x] Fix: registered && postPage click close icon
