### ISSUE TITLE
 Fix: startPage && in onboarding  process nextBtn position

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#313]
## ☕ 기능
![image](https://github.com/7-7-2/DDocker_FE/assets/115582699/b5c9f9d1-f8d7-4683-8ee0-5012891c26d8)
![image](https://github.com/7-7-2/DDocker_FE/assets/115582699/c80dec42-483b-4cfa-a087-07ecd24cff06)

- 베타 테스트 유저 의견 반영 가입 절차 UX 개선

## 🪴 TODO

- [x] 회원가입 절차 브랜드 선택 컴포넌트 내부 플로팅 버튼 하단고정
- [x] 선호 브랜드 선택 문구 변경
- [x] 메인페이지 카페인 총 섭취량 문구 => 오늘 일일 카페인 권장량 기준 문구 변경
