### ISSUE TITLE
Feat: add ristretto option in CoffeeOptionSelect

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#314]
## ☕ 기능
![image](https://github.com/7-7-2/DDocker_FE/assets/125563995/e2d8c1a6-a6fb-4cc2-bb0f-e6fd289d1478)
![image](https://github.com/7-7-2/DDocker_FE/assets/125563995/b462adb6-6e44-4e1e-82aa-334bb5d6499b)

- 커피 등록하기(`PostRegister.tsx`) 및 메인 커피 조회시(`CoffeeOptionSelection.tsx`) 연하게 옵션 추가

## 🪴 TODO

- [x] PostRegister.tsx 옵션 추가
- [x] 카페인 연산로직에 반영 
- [x] DB 테이블 수정 (column => `ristretto: boolean`)
- [x] trigger수정(확인 필요) 
- [x] client/server api format(`ristretto: boolean`) 수정
