### ISSUE TITLE
 Fix: Presigned Upload Url response, Weekly Popular List data fetching  

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#324]
## ☕ 기능

- fix WeeklyPopularList data fetching
- refactoring PostRegister logic
- fix getPresignedUploadUrl response
- set default font size

## 🪴 TODO

- [x] Feat: update pwa version
- [x] Fix: WeeklyPopularList data fetching
- [x] Refactor: PostRegister
- [x] Fix: getPresignedUploadUrl response
- [x] Design: set default font size
- [x] Fix:  add conditional statement getPopularList
