### ISSUE TITLE
 Fix: PostDetail Page && Img Error design 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#329]
## ☕ 기능

<img width="326" alt="image" src="https://github.com/user-attachments/assets/ae2467b4-a972-4a65-992f-25b6b9d5a4c4">
<img width="327" alt="image" src="https://github.com/user-attachments/assets/a994cd2f-ec39-42d9-a212-98778955ab36">

- 게시물 상세 페이지 이미지 오류 디자인 수정

## 🪴 TODO

- [x] Refactor: imgErrorText constants
- [x] Feat: PostDetail Page && Img Error design
- [x] Fix: img error message
