### ISSUE TITLE
Fix: start page cache data 없는경우 생기는 이슈 수정 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#85]
## ☕ 기능

- start Page 오류 수정

## 🪴 TODO

- [x] Fix: nickname 설정 오류 수정
- [x] Fix: cacheData 부재시 빈화면 로드 오류 수정
- [x] Feat: Brand nmae 영> 한 converter util 함수 추가
- [x] Feat: BrandList 추출 util 함수 추가
- [x] Feat: selectFavBrand.tsx 브랜드 데이터 및 로고 추가
- [x] Feat: brand logo png 파일 추가
