### ISSUE TITLE
 Fix: PWA A2HS 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#89]
## 🪴 TODO

- [x] A2HS(홈 화면에 추가) 시 manifest.json 내 "theme_color" 추가
- [x] index.html 내 <meta name="mobile-web-app-capable" content="yes" /> 추가
- [x] manifest.json 내 'start_url' 속성 수정 url => absolute path(/) (https://web.dev/articles/webapks?hl=ko)
