### ISSUE TITLE
 Refactor: firebase > server api 변경

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#90]
## ☕ 기능

- todo

<img width="300" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/6bf27126-dde6-49c7-86f7-b74ac49e127a">

- firebase연결 로직 server api로 변경

## 🪴 TODO

- [ ] Refactor: social auth 
- [ ] Refactor: page_start
- [ ] Refactor: check nickname api
