### ISSUE TITLE
 Feat: post.api file firebase > server api 변경

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#92]
## ☕ 기능

- post.api file firebase > server api 변경
- error 임시 수정
<img width="286" alt="image" src="https://github.com/7-7-2/DDocker_FE/assets/125563995/648deba5-28b6-461a-b8a9-01e62a0e20e8">

## 🪴 TODO

- [x] Refactor: getTodayCoffeeInfo type 수정
- [x] Fix: error 임시 수정
- [x] Refactor: getTodayCoffeeInfo data 연결
- [x] Refactor: setPostRegist, getTodaycoffeeInfo api
