### ISSUE TITLE
Refactor: WeeklyPopular api, Brand api 연결 

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_FE#93]
## ☕ 기능

- WeeklyPopular api
- Coffee Brand api 연결  

## 🪴 TODO

- [x] Refactor: coffeeSelection state 수정, reset state 추가
- [x] Refactor: getTodayCoffeeInfo && dataList.length > allCount
- [x] Refactor: getCoffeeMenu && setBrandList, setMenuList
- [x] Feat: getCoffeeMenu api
- [x] Refactor: types.ts 수정
- [x] Refactor: dataList data 변경
- [x] Feat: getWeeklyPopular api
