### ISSUE TITLE
Feat: PostDetail 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker_FE#94]
## ☕ 기능
[Screen recording 2024-02-24 10.41.03 PM.webm](https://github.com/7-7-2/DDocker_FE/assets/115582699/e5952d43-8b09-4772-8ea6-966a3f05de89)

- 게시글 상세 정보 조회 및 댓글, 답글 조회
- 기존 컴포넌트 추가적 분리(CommentProto => Comment, Reply 공통사용, Presentational component)
- 게시글 생성시점 확인 용도 utils 생성(timestampToDate) => Posts페이지에서도 재사용예정
- MiniProfile prop 수정(NickName=>nickname)

## 🪴 TODO

- [ ] 댓글 작성 및 답글 작성
- [ ] 팔로잉 중인 게시글 조회(feed)
- [ ] 게시글 좋아요 확인 API연결(getMyLikeOnPost)
- [ ] 공유기능 활성화
- [ ] import 정리
